#:schema node_modules/wrangler/config-schema.json
name = "laeseroller-skolechips"
compatibility_date = "2024-04-03"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[vars]
# Her kan du tilføje miljøvariabler, hvis det er nødvendigt
# Bemærk: Hemmeligheder som API-nøgler bør sættes i Cloudflare Dashboardet
