#:schema node_modules/wrangler/config-schema.json
name = "laeseroller-skolechips"
compatibility_date = "2024-04-03"

[assets]
directory = "./dist"

[build]
command = "npm run build"

[vars]
# API-noegler boer saettes i Cloudflare Dashboardet
